### ISSUE TITLE
Array object data not encrypted

### ISSUE THREAD

**Issue by djemrose** [jsdream/mongoose-advanced-encryption#1]
This plugin has been very useful for my project. One thing I am struggling with currently is that I am trying to encrypt properties of an array but they do not seem to be encrypted at all.

Schema definition is as so - there are many more properties I would like to encrypt inside the array but I'll demonstrate one:
```
timesheets: [{
    ordinary_total: {
        type: String,
        trim: true,
        required: 'Please fill in <strong>Ordinary Total</strong>!',
        encrypt: true
    }
}]
```

This results in unencrypted normal data in the array for "ordinary_total". However root level Schema properties are encrypted without issue like so:

```
ordinary_total: {
    type: String,
    trim: true,
    required: 'Please fill in <strong>Ordinary Total</strong>!',
    encrypt: true
}
```

Is this because the encryption only works on String schema types? So it doesn't work as it is a String inside an Array?

Any guidance would be great.
Cheers

**Comment by jsdream** [comment]
Hi @djemrose! I'm glad to hear you found this plugin useful in your project.

Unfortunately, this encryption plugin doesn't support encryption of separate object fields in an array at the moment. This is not implemented because this would add additional complexity to the encryption/decryption process and wasn't a requirement in our company. We decided to not sacrifice performance for functionality we are not planning to use.

I'd suggest you reconsider your model structure instead if possible.
